name: DynPlaceholderAPI-Bungee
version: 0.1.0
author: veir1
description: Set dynamic placeholders with the IP used by the player when entering a server through BungeeCord.
main: me.veir1.dynplaceholderapi.bungee.DynPlaceholderAPIBungee