name: DynPlaceholderAPI-Bukkit
version: 0.1.0
description: Set dynamic placeholders with the IP used by the player when entering a server through BungeeCord.
main: me.veir1.dynplaceholderapi.bukkit.DynPlaceholderAPIBukkit
softdepend: [PlaceholderAPI]
commands:
  dynpapi:
    description: Plugin information.
  dynpapireload:
    description: Reload the plugin config.